"""phase1 guide upload fields

Revision ID: 49bcebaa61c3
Revises: a54a1aa158da
Create Date: 2026-02-01 14:11:31.641875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bcebaa61c3'
down_revision: Union[str, Sequence[str], None] = 'a54a1aa158da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leveling_guides', sa.Column('original_filename', sa.Text(), nullable=True))
    op.add_column('leveling_guides', sa.Column('mime_type', sa.Text(), nullable=True))
    op.add_column('leveling_guides', sa.Column('pdf_path', sa.Text(), nullable=False))
    op.create_index('ix_leveling_guides_company_id', 'leveling_guides', ['company_id'], unique=False)
    op.create_index('ix_leveling_guides_status_created_at', 'leveling_guides', ['status', 'created_at'], unique=False)
    op.drop_column('leveling_guides', 'source_filename')
    op.drop_column('leveling_guides', 'pdf_storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leveling_guides', sa.Column('pdf_storage_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leveling_guides', sa.Column('source_filename', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_leveling_guides_status_created_at', table_name='leveling_guides')
    op.drop_index('ix_leveling_guides_company_id', table_name='leveling_guides')
    op.drop_column('leveling_guides', 'pdf_path')
    op.drop_column('leveling_guides', 'mime_type')
    op.drop_column('leveling_guides', 'original_filename')
    # ### end Alembic commands ###
