"""create initial tables

Revision ID: a248f821a148
Revises: 
Create Date: 2026-01-29 20:08:36.438165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a248f821a148'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_url')
    )
    op.create_table('leveling_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role_title', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('pdf_storage_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['leveling_guides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_id', 'name', name='uq_competencies_guide_name')
    )
    op.create_index('ix_competencies_guide_position', 'competencies', ['guide_id', 'position'], unique=False)
    op.create_table('guide_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['leveling_guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['leveling_guides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_id', 'code', name='uq_levels_guide_code')
    )
    op.create_index('ix_levels_guide_position', 'levels', ['guide_id', 'position'], unique=False)
    op.create_table('guide_cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=True),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['leveling_guides.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['guide_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competency_id', 'level_id', name='uq_cells_competency_level')
    )
    op.create_index('ix_cells_guide', 'guide_cells', ['guide_id'], unique=False)
    op.create_table('parse_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_artifact_id', sa.UUID(), nullable=True),
    sa.Column('output_artifact_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['leveling_guides.id'], ),
    sa.ForeignKeyConstraint(['input_artifact_id'], ['guide_artifacts.id'], ),
    sa.ForeignKeyConstraint(['output_artifact_id'], ['guide_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cell_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('examples_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['guide_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generations_cell_created', 'cell_generations', ['cell_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generations_cell_created', table_name='cell_generations')
    op.drop_table('cell_generations')
    op.drop_table('parse_runs')
    op.drop_index('ix_cells_guide', table_name='guide_cells')
    op.drop_table('guide_cells')
    op.drop_index('ix_levels_guide_position', table_name='levels')
    op.drop_table('levels')
    op.drop_table('guide_artifacts')
    op.drop_index('ix_competencies_guide_position', table_name='competencies')
    op.drop_table('competencies')
    op.drop_table('leveling_guides')
    op.drop_table('companies')
    # ### end Alembic commands ###
