from enum import Enum

class GuideStatus(str, Enum):
    QUEUED = "QUEUED"

    EXTRACTING_TEXT = "EXTRACTING_TEXT"
    TEXT_EXTRACTED = "TEXT_EXTRACTED"
    FAILED_BAD_PDF = "FAILED_BAD_PDF"

    PARSING_MATRIX = "PARSING_MATRIX"
    MATRIX_PARSED = "MATRIX_PARSED"
    FAILED_PARSE = "FAILED_PARSE"

    GENERATING_EXAMPLES = "GENERATING_EXAMPLES"
    DONE = "DONE"
    FAILED_GENERATION = "FAILED_GENERATION"
